version: "3.7"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - user=carlos
                - uid=1000
                - NODE_VERSION=14
                - NPM_VERSION=7
                - CURL_VERSION=latest
                - INSTALL_NODE=true
                - INSTALL_NPM=true
                - INSTALL_CURL=true
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./backend:/var/www
        depends_on:
            - redis
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./backend:/var/www
            - ./backend/docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # db mysql
    db:
        image: mysql:5.7.22
        platform: linux/x86_64
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
            MYSQL_USER: ${DB_USERNAME:-username}
        volumes:
            - ./backend/.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3308:3306"
        networks:
            - laravel
    #iamge frontend
    image_front:
        build:
            context: .
            dockerfile: Dockerfile-front
        restart: unless-stopped
        working_dir: /app
        volumes:
            - ./frontend:/app
            - /app/node_modules
        ports:
            - "3000:3000"


    # redis
    redis:
        image: redis:latest
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
