# Use Node 18 image as base
FROM node:18


RUN mkdir /app
# Set working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY ./frontend/package.json ./frontend/package-lock.json ./

#RUN npm install -g npm@9.1.8


#USER node
# Install dependencies
RUN yarn install

# Copy the rest of the application code to the container
COPY . .

# Expose the port your app runs on
EXPOSE 3000

# Define the command to run your app
CMD ["yarn", "run", "dev", "--host"]